### ISSUE TITLE
Maximize Character Gesture Behaves Differently on Two Machines

### ISSUE THREAD

**Issue by elstgav** [aaronkollasch/jitouch#19]
_So_ glad to see Jitouch back! 🎉. Thank you for working on this 🙏🏻.

I just installed Jitouch on my work and home laptops, and am seeing different behavior on them. On my home laptop, a MacBook Pro 15-inch, 2016, when I use the character gestures to maximize windows left or right, they snap instantly. And frustratingly, the gesture doesn’t work on Chrome windows.

However, on my work laptop, a 16-inch 2019 MacBook Pro, when I use the gestures, windows smoothly animate to their new position, and Chrome windows work just fine. What’s the expected behavior here? Are windows expected to smoothly transition between maximize states?

**Comment by elstgav** [comment]
Update: The Chrome issue seems to be related an extension or something. When I open incognito windows or log into a different profile, the maximize function works fine. Very strange, I don’t know how an extension could be interfering with the behavior 🤔

**Comment by aaronkollasch** [comment]
Hmm, yeah I do see the second issue - resize gestures aren't working on Chrome after navigating to a new site. The character gesture itself seems to be detected. It's possible Jitouch is getting the wrong window with [getForemostApp()](https://github.com/aaronkollasch/jitouch/blob/c722b388ee3e9eada1fc451a84a80fb8246a63cb/jitouch/Jitouch/Gesture.m#L211).

On my 2021 MBP I don't see a smooth animation, just snapping. It may be OS-determined behavior, based on this call to `AXUIElementSetAttributeValue`: https://github.com/aaronkollasch/jitouch/blob/c722b388ee3e9eada1fc451a84a80fb8246a63cb/jitouch/Jitouch/Gesture.m#L257-L265

**Comment by ONEKENO** [comment]
Hello,

Any solution for resized gestures aren't working on Chrome?

Thanks

**Comment by aaronkollasch** [comment]
So my Google Chrome wasn't working with the Maximize gestures, but then I navigated to chrome://accessibility and the gestures started working.

The issue was `getForemostApp()` returning null when [`AXUIElementCopyAttributeValue()`](https://developer.apple.com/documentation/applicationservices/1462085-axuielementcopyattributevalue) of `kAXFocusedApplicationAttribute` returned `kAXErrorNoValue`; function linked below.

https://github.com/aaronkollasch/jitouch/blob/2c45eedf06bd2e82b00e9b93c8e8bebc8e3d0c09/jitouch/Jitouch/Gesture.m#L212

Therefore, I suspect Google Chrome may have been hiding itself from the accessibility API by default. See this [stackoverflow answer](https://stackoverflow.com/questions/37365545/reaching-accessibility-hierarchy-in-google-chrome-on-os-x/37421361#37421361) for another instance of this behavior.

Just visiting the accessibility page seems to have fixed it for me, and now I can't get gestures to stop working, even if I uncheck all the accessibility features. Let me know if that fixes things for you.

**Comment by ONEKENO** [comment]
The gesture works after checking the boxes "Native accessibility API support" and "Web accessibility" but after restarting the browser the checkings are gone and also gesture stops working. Is there any way to save the checking after relaunch?
It's the same with Brave.
Thanks.

**Comment by aaronkollasch** [comment]
It looks like actually a simple fix, I'll include it in the next beta.

**Comment by aaronkollasch** [comment]
Beta now released at https://github.com/aaronkollasch/jitouch/releases/tag/v2.82-beta.2. Let me know if it works.

**Comment by ONEKENO** [comment]
> Beta now released at https://github.com/aaronkollasch/jitouch/releases/tag/v2.82-beta.2. Let me know if it works.

It's now working very well even after relaunching the browser. Well done. Thank you very much.

**Comment by aaronkollasch** [comment]
Awesome!
